import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  SignInButton,
  UserButton,
} from "@clerk/nextjs";
import { Header } from "./header";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Neon-Next-Clerk-Inngest Example",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // this weird control statement is due to some kind of issue getting Clerk working
  // see the discussion in: https://github.com/clerk/javascript/issues/2736#issuecomment-2239873782
  if (false) {
    return (
      <ClerkProvider>
        <html lang="en">
          <body className={inter.className}>
            <header>
              <SignedOut>
                <SignInButton />
              </SignedOut>
              <SignedIn>
                <UserButton />
              </SignedIn>
            </header>
            <main>{children}</main>
          </body>
        </html>
      </ClerkProvider>
    );
  } else {
    return (
      <ClerkProvider>
        <html lang="en">
          <body className={inter.className}>
            <header>
              <Header />
            </header>
            <main>{children}</main>
          </body>
        </html>
      </ClerkProvider>
    );
  }
}
